config/routes.rb
Rails.application.routes.draw do
  get 'messages/index'

  get 'lobby/index'

  get 'game_tables/index'

  get 'games/index'

  get 'games/create'

  get 'games/newgame'

  get 'games/rules'

  get 'games/update/:game_id' => "games#update", :as => :update_game

  get 'lobby/update/:game_id' => "lobby#update", :as => :update_with_game_id

  get "games/update/:game_id" => "games#update"

  post "games/index" => "games#index"

  post "games/update/:game_id" => "games#update"

  post "lobby/update/:game_id" => "lobby#update"

  post "game/update/:game_id/:card_id/:user_id" => "game#update"

  root 'games#rules'

  post 'login' => 'messages#login'
  get 'messages/welcome'
  resources :messages, only: [:create]
  resources :games
  devise_for :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>uno</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= pusher_include_tag '2.2' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body>
<!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
             
                <%= link_to "Project-Uno", root_url, class: "navbar-brand"%>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    
                    <%- if current_user %>
                        <li>
                        <%= link_to "New Game", games_newgame_path %>
                        </li>
                        <li>
                        <%= link_to "Join Game", lobby_index_path %>
                        </li>
                        <li>
                        <%= link_to "Profile", edit_user_registration_path %>
                        </li>
                        <li> 
                            <%= link_to "Logout", destroy_user_session_path, method: :delete, confirm: "Are you sure?" %>
                        </li>
                    <% else %>
                    <li>
                        <%= link_to "Login", new_user_session_path %>
                    </li>
                    <li>
                        <%= link_to "Sign Up", new_user_registration_path %>
                    </li>
                    <% end %>
                    <li>
                        <%= link_to "Rules", games_rules_path %>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <!-- Page Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-left">

                <% flash.each do |a, b| %>
                    <div class="alert alert-success"> <%= b %> </div>
                    <%end%>
            </div>
        </div>
        <!-- /.row -->
        <%= yield%>
    </div>
    <!-- /.container -->
   <style>body{padding-top:70px;}</style>
   
</body>
</html>